name: Build
on: push
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: clone-down
        uses: actions/checkout@v2
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
      - name: Build with gradle
        run: ci/build-app.sh
