name: JAVA CI
on: push
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: clone-down
        uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with: 
          name: code
          path: .
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [clone]
    steps:
      - name: retrive Repo
        run: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Build with gradle
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
        
