name: Build
on: push
jobs:
  clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone
        uses: actions/checkout@v2
      - name: Build
        run: ci/build-app.sh
